FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libgl1 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_grpc.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements_grpc.txt

COPY . .

RUN python -m grpc_tools.protoc \
    -I. \
    --python_out=. \
    --grpc_python_out=. \
    interview.proto

EXPOSE 50051

CMD ["python", "grpc_server.py"]
